import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import FlyonuiScript from "../components/FlyonuiScript";
import "./globals.css";

// In a client-side component or a global script
// import { Observer } from 'tailwindcss-intersect';
import { Header } from "../components/Header";

// Start the observer, typically once in your application's lifecycle
// Observer.start();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-svh`}
      >
        <FlyonuiScript />
          <div className="flex h-full overflow-hidden items-center justify-center font-sans bg-[#daaf9a]" >
            <div className="flex w-full h-full"
              style={{
                backgroundImage:
                  `
                    radial-gradient(
                      circle at top left,
                      #faf3ec,
                      transparent 90%
                    )
                  `,
                filter: "blur(0px)",
                backgroundRepeat: "no-repeat",
              }}
            >
              <main className="w-full h-full px-10 py-10 overflow-auto">
                <Header />
                {children}
              </main>
            </div>
          </div>
      </body>
    </html>
  );
}
